language: node_js
sudo: false
env:
  global:
    secure: IAAGZHGoQ/5QBT3y6uhFGeA73wBxksG9EAFVt8A0+k20UzLKwUmgbSSpftytnkYYTcmkEWVWyQ7Hx0ROflkpamIlYzWPkGunimQGrjjp73sYJyZ/ur8prvqSN5CBp+r7YR4f+OA8rOdpJ4PVZC+KmvSZsmRlaCiJS2pQbCdC7bU=
before_install:
- npm install -g jspm
- jspm config registries.github.auth $JSPM_GITHUB_AUTH_TOKEN
node_js:
- '0.12'
- '0.10'
notifications:
  irc:
    channels: chat.freenode.net#laxarjs
    template: '%{repository_slug} (%{commit}) [%{branch}]: %{message}'
